# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app import xml_service_pb2 as xml__service__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in xml_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class XmlQueryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TopGdp = channel.unary_unary(
                '/xmlservice.XmlQueryService/TopGdp',
                request_serializer=xml__service__pb2.TopGdpRequest.SerializeToString,
                response_deserializer=xml__service__pb2.TopGdpResponse.FromString,
                _registered_method=True)
        self.CountriesByCurrency = channel.unary_unary(
                '/xmlservice.XmlQueryService/CountriesByCurrency',
                request_serializer=xml__service__pb2.CurrencyStatsRequest.SerializeToString,
                response_deserializer=xml__service__pb2.CurrencyStatsResponse.FromString,
                _registered_method=True)
        self.PopulationFilter = channel.unary_unary(
                '/xmlservice.XmlQueryService/PopulationFilter',
                request_serializer=xml__service__pb2.PopulationFilterRequest.SerializeToString,
                response_deserializer=xml__service__pb2.PopulationFilterResponse.FromString,
                _registered_method=True)


class XmlQueryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TopGdp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountriesByCurrency(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PopulationFilter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_XmlQueryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TopGdp': grpc.unary_unary_rpc_method_handler(
                    servicer.TopGdp,
                    request_deserializer=xml__service__pb2.TopGdpRequest.FromString,
                    response_serializer=xml__service__pb2.TopGdpResponse.SerializeToString,
            ),
            'CountriesByCurrency': grpc.unary_unary_rpc_method_handler(
                    servicer.CountriesByCurrency,
                    request_deserializer=xml__service__pb2.CurrencyStatsRequest.FromString,
                    response_serializer=xml__service__pb2.CurrencyStatsResponse.SerializeToString,
            ),
            'PopulationFilter': grpc.unary_unary_rpc_method_handler(
                    servicer.PopulationFilter,
                    request_deserializer=xml__service__pb2.PopulationFilterRequest.FromString,
                    response_serializer=xml__service__pb2.PopulationFilterResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xmlservice.XmlQueryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('xmlservice.XmlQueryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class XmlQueryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TopGdp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xmlservice.XmlQueryService/TopGdp',
            xml__service__pb2.TopGdpRequest.SerializeToString,
            xml__service__pb2.TopGdpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountriesByCurrency(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xmlservice.XmlQueryService/CountriesByCurrency',
            xml__service__pb2.CurrencyStatsRequest.SerializeToString,
            xml__service__pb2.CurrencyStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PopulationFilter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xmlservice.XmlQueryService/PopulationFilter',
            xml__service__pb2.PopulationFilterRequest.SerializeToString,
            xml__service__pb2.PopulationFilterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
