# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: xml_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'xml_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11xml_service.proto\x12\nxmlservice\"@\n\rTopGdpRequest\x12\x12\n\ndocumentId\x18\x01 \x01(\x03\x12\x0c\n\x04year\x18\x02 \x01(\t\x12\r\n\x05limit\x18\x03 \x01(\x05\"Q\n\nTopGdpItem\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04iso2\x18\x02 \x01(\t\x12\x0c\n\x04iso3\x18\x03 \x01(\t\x12\x0c\n\x04year\x18\x04 \x01(\t\x12\x0b\n\x03gdp\x18\x05 \x01(\x01\"7\n\x0eTopGdpResponse\x12%\n\x05items\x18\x01 \x03(\x0b\x32\x16.xmlservice.TopGdpItem\"9\n\x14\x43urrencyStatsRequest\x12\x12\n\ndocumentId\x18\x01 \x01(\x03\x12\r\n\x05limit\x18\x02 \x01(\x05\"/\n\x0c\x43urrencyStat\x12\x10\n\x08\x63urrency\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"@\n\x15\x43urrencyStatsResponse\x12\'\n\x05items\x18\x01 \x03(\x0b\x32\x18.xmlservice.CurrencyStat\"j\n\x17PopulationFilterRequest\x12\x12\n\ndocumentId\x18\x01 \x01(\x03\x12\x15\n\rminPopulation\x18\x02 \x01(\x03\x12\x15\n\rmaxPopulation\x18\x03 \x01(\x03\x12\r\n\x05limit\x18\x04 \x01(\x05\"D\n\x0ePopulationItem\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\npopulation\x18\x02 \x01(\x03\x12\x10\n\x08worldPct\x18\x03 \x01(\x01\"E\n\x18PopulationFilterResponse\x12)\n\x05items\x18\x01 \x03(\x0b\x32\x1a.xmlservice.PopulationItem2\x8d\x02\n\x0fXmlQueryService\x12?\n\x06TopGdp\x12\x19.xmlservice.TopGdpRequest\x1a\x1a.xmlservice.TopGdpResponse\x12Z\n\x13\x43ountriesByCurrency\x12 .xmlservice.CurrencyStatsRequest\x1a!.xmlservice.CurrencyStatsResponse\x12]\n\x10PopulationFilter\x12#.xmlservice.PopulationFilterRequest\x1a$.xmlservice.PopulationFilterResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xml_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOPGDPREQUEST']._serialized_start=33
  _globals['_TOPGDPREQUEST']._serialized_end=97
  _globals['_TOPGDPITEM']._serialized_start=99
  _globals['_TOPGDPITEM']._serialized_end=180
  _globals['_TOPGDPRESPONSE']._serialized_start=182
  _globals['_TOPGDPRESPONSE']._serialized_end=237
  _globals['_CURRENCYSTATSREQUEST']._serialized_start=239
  _globals['_CURRENCYSTATSREQUEST']._serialized_end=296
  _globals['_CURRENCYSTAT']._serialized_start=298
  _globals['_CURRENCYSTAT']._serialized_end=345
  _globals['_CURRENCYSTATSRESPONSE']._serialized_start=347
  _globals['_CURRENCYSTATSRESPONSE']._serialized_end=411
  _globals['_POPULATIONFILTERREQUEST']._serialized_start=413
  _globals['_POPULATIONFILTERREQUEST']._serialized_end=519
  _globals['_POPULATIONITEM']._serialized_start=521
  _globals['_POPULATIONITEM']._serialized_end=589
  _globals['_POPULATIONFILTERRESPONSE']._serialized_start=591
  _globals['_POPULATIONFILTERRESPONSE']._serialized_end=660
  _globals['_XMLQUERYSERVICE']._serialized_start=663
  _globals['_XMLQUERYSERVICE']._serialized_end=932
# @@protoc_insertion_point(module_scope)
